---
title: "Terms and definitions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{terms}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Main assumptions

1. General logic:
    1. Operator OR is valid for a and b means: I) a, II) b, III) a and b
    1. Operator AND is valid for a and b only when we have a and b at the same time.
2. Authors’ interpretation always supersedes ours.
3. Interactee and interactor
    1. An interactee is always acted upon by an interactor. If the publication uses words like “co-incubation” and from the text itself it is not clear how to distinct between interactor and interactor and the authors study the effect on Protein A on Protein B and vice versa, create two separate interactions in the questionnaire: one where A is an interactor over B and another one, where B is an interactor over A.
    1. Database contains only interactions between two amyloids. The form already contains a list of appropriate amyloid proteins. If one of the participants of the interaction is a non-amyloid protein, it shouldn’t be included in the database. The only exceptions are: a) non-aggregating homologues of known amyloid proteins b) non-aggregating mutants of amyloid proteins c) non-aggregating fragments of amyloid proteins.
    1. If the interactee or interactor is a) a mutant of an amyloid protein OR b) a fragment of an amyloid protein OR c) a taxonomic variant of an amyloid protein, we still add them to the database under the name of the original protein. However, in this case be extremely precise with the actual sequence of the interactee/interactor.
If the sequence of the interactor or the interactee contains modified amino acid residues, we do not supply this information in the sequential data. Instead, this information should be present in the general remarks field.
    1. If the sequence of the interactor or the interactee contains (due to modifications) non-amino acids or nonbiogenic amino acids, this interaction is rejected.
4. Interaction
    1. Many questions and definitions employ the term aggregation. For the purpose of the manuscript curation, we understood aggregation as the aggregation to the level of mature fibril (fibrillization). If the interactor accelerates the speed of the oligomer formation, but they never aggregate into the level of mature fibrils (fibrillization does not occur), it is not an acceleration in our understanding. Therefore, check not only the resulting kinetics, but search also for microscopy images (or any similar confirmation of the fibrillization).
    1. In the case of different interaction of the same two amyloids, when these differences stem from the different amyloid formation level (monomer, oligomer, fiber), pH, concentration, temperature or other conditions, we note this information as an unstructured comment in the general remarks section. Nevertheless, submit these aggregations as two (or more) different aggregations highlighting the different effects.
    1. Seeding means the induction of interactee’s aggregation by adding interactor’s molecules. Therefore, seeding should be considered as: positive answers for questions Q1 AND (Q2 OR Q3) AND Q4 AND Q5. Seeding does not exclude heterogeneous fibrils (Q6), but cannot imply it.
    1. We focus only on interactions studied in vitro.
    1. We consider only two-party interactions. The database does not contain interactions with more than two participants. The only exception is when two out of three participants are the same protein in a different aggregation level.
We assume that there are six main scenarios that can occur during the interaction of two amyloid proteins (see the figure below). We design the questions to discriminate between these scenarios. Q1 differentiates between scenarios I (no effect on kinetics) II and III (inhibited aggregation) as well as IV, V and VI (acceleration). Q2 discriminates between scenarios IV and V/VI. Q3 discriminate between scenarios V and VI.

